%********************************Hechos*****************************+
%Chatbot: aridad 2, corresponde a una lista que contiene las posibles respuestas para las frases ingresadas por el usuario.
 chatbot(chatbot,[" HOGWARTSBOT: Bienvenido a la Hogwarts, hoy sere tu guia en el castillo, En que puedo ayudarte ? ", " HOGWARTSBOT: Bienvenido a Hogwarts, hoy sere tu guia en el castillo,  En que puedo ayudarte? ", " HOGWARTSBOT: Bienvenido a Hogwarts, hoy sere tu guia en el castillo,  En que puedo ayudarte? ",
       " HOGWARTSBOT: Hay cuatro casas en Hogwarts, ¿cual es la tuya? ", " HOGWARTSBOT: A que casa de Hogwarts perteneces? ", " HOGWARTSBOT: Todas las casas tienen algo bueno y tambien malo, Cual es la tuya? ",
       " HOGWARTSBOT: Ravenclaw es una de las cuatro casas que componen el Colegio Hogwarts de Magia y Hechiceria, fundada por Rowena Ravenclaw, quien tuvo una hija, cuyo fantasma es la Dama Gris. Que mas quieres saber? ", "  HOGWARTSBOT: La casa Ravenclaw premia el aprendizaje, la sabiduria, el ingenio, y el intelecto de sus miembros. Que mas quieres saber? ", "HOGWARTSBOT: Para entrar a la sala comun de ravenclaw, se debe resolver un acertijo que no siempre es el mismo, formulado por un aldaba de bronce con forma de aguila en una puerta sin picaporte. Que mas quieres saber? ",
       " HOGWARTSBOT:  Fundada por Godric Gryffindor. Su animal emblematico es el leon y sus colores son el rojo escarlata y el dorado. Minerva McGonagall es la más reciente jefa de la casa. Que mas quieres saber? ", " HOGWARTSBOT: La sala comun de Gryffindor esta localizada en la Torre de Gryffindor, la entrada esta localizada en el septimo piso y esta custodiada por el retrato de la Dama Gorda, que utiliza un vestido rosa. Ella permite la entrada solamente si la clave es la correcta (cambia regularmente).  Que mas quieres saber? ", " HOGWARTSBOT: La Casa de Gryffindor estima el coraje, asi como la osadia, el temple y la caballerosidad, asi, sus miembros se caracterizan por ser valientes aunque a veces hasta el punto de ser imprudentes.  Que mas quieres saber? ",
       " HOGWARTSBOT: La sala comun de Slytherin esta ubicada detras de la entrada escondida en las mazmorras, sus ventanas proporcionan una luz verde, pues dan a las profundidades del lago de Hogwarts. Los alumnos de Slytherin, a menudo ven al calamar gigante nadando rapidamente y, a veces, criaturas aun mas interesantes.  Que mas quieres saber? ", " HOGWARTSBOT: Los alumnos de Slytherin tienden a ser ambiciosos, inteligentes, astutos, lideres fuertes, y orientados hacia los logros. Tambien tienen muy desarrollado el instinto de supervivencia. Que mas quieres saber? ", "HOGWARTSBOT: El Sombrero Seleccionador dice que la pureza de sangre es un factor en la selección de Slytherin. ",
       " HOGWARTSBOT: Hufflepuff es una de las cuatro casas del Colegio Hogwarts de Magia y Hechiceria. Su fundadora es la bruja medieval Helga Hufflepuff. La jefa de la casa es Pomona Sprout. Que mas quieres saber?  ", " HOGWARTSBOT: Los estudiantes de esta casa son conocidos por ser trabajadores, amigables, leales y sin prejuicios. Debido a sus valores, los hufflepuffs no son tan competitivos como las otras casas, o son mas modestos con respecto a sus logros. Que mas quieres saber? ", " HOGWARTSBOT:  Cedric Diggory llevo a su casa a un esplendor poco comun como capitan de Quidditch y mas tarde como Campeon de Hogwarts en el Torneo de los Tres Magos en 1994.  Que mas quieres saber? ",
       " HOGWARTSBOT: El Colegio Hogwarts de Magia y Hechiceria es un internado magico ubicado en Escocia. El castillo se ubica en unas montañas cercanas a un lago. Te interesa algo mas? ", "HOGWARTSBOT:  Los encantamientos que protegen al castillo son clasificados como encantamientos anti-Aparicion y encantos repelentes de Muggles, que lo hacen que ellos vean unas ruinas antiguas con un letrero que dice 'Peligro, prohibido el paso' en lugar del castillo. Quieres saber algo mas? ", " HOGWARTSBOT: El lema de Hogwarts es: 'Draco dormiens nunquam titillandus' . La traduccion es: Nunca hagas cosquillas a un dragon dormido. Quieres saber algo mas? ",
       " HOGWARTSBOT: Algunas materias son: Adivinacion, defensa contra las artes oscuras y cuidado de criaturas magicas, ¿Quieres saber de alguna?  ", " HOGWARTSBOT: Las asignaturas mas populares son Defensa contra las artes oscuras y pociones ¿Quieres saber algo mas? ", " HOGWARTSBOT: Sin duda la mas divertida es cuidado de criaturas magicas, Te puedes imaginar montar un hipogrifo?",
       " HOGWARTSBOT: Defensa Contra las Artes Oscuras es una asignatura consistente en la enseñanza de variadas tecnicas para contrarrestar las Artes Oscuras y las criaturas de este tipo. Necesitas alguna otra informacion ? ", " HOGWARTSBOT: Es una asignatura que se enseña desde el primer año al quinto en el Colegio Hogwarts de Magia y Hechiceria, con la opcion de un curso EXTASIS en los años sexto y septimo, siempre que se respete la nota minima, que varia segun el profesor. Hay alguna otra cosa que quieras saber?" ," HOGWARTSBOT: Desde que entro a trabajar en Hogwarts, Severus Snape quiso enseñar Defensa Contra las Artes Oscuras. Sin embargo, Dumbledore no lo permitio y en cambio lo convirtio en profesor de Pociones. Alguna otra cosa que quieras saber? ",
       " HOGWARTSBOT: Transformaciones es una clase impartida en el Colegio Hogwarts de Magia y Hechiceria. Enseña el arte de cambiar la forma y apariencia de un objeto o al mago mismo. Necesitas algo mas?",  " HOGWARTSBOT: Transformaciones es una asignatura obligatoria para todos los alumnos desde el primer año, con la opcion de cursos para los EXTASIS en sexto y septimo año. Necesitas algo mas? ", " HOGWARTSBOT:  Minerva McGonagall fue la profesora de Transformaciones en Hogwarts desde 1956 hasta 1998, año en el que se volvio Directora del Colegio. Necesitas algo mas?",
       " HOGWARTSBOT: Este antiguo y misterioso encantamiento conjura un guardian magico, una proyeccion de todos tus sentimientos alegres. Quieres saber algo mas? ", " HOGWARTSBOT: El Encantamiento patronus es complicado, y muchas brujas y magos son incapaces de producir un patronus completamente corporeo. ", " HOGWARTSBOT: De acuerdo a la leyenda, uno de los Patronus mas famosos de todos los tiempos fue un humilde raton, que creo un joven mago llamado Ilyius. Ilyius lanzo el encantamiento Patronus cuando su villa fue atacada por el mago tenebroso Raczidian y su ejercito de dementores. otra cosa que quieras saber? ",
       " HOGWARTSBOT: Los Dementores estan entre las criaturas mas nauseabundas del mundo. Infestan los lugares mas oscuros y mas sucios. Quieres saber algo mas? ", " HOGWARTSBOT: Si alguien se acerca mucho a un Dementor, este le quitara hasta el ultimo sentimiento positivo y hasta el ultimo recuerdo dichoso. ", " HOGWARTSBOT: Los Dementores son seres horribles de gran estatura, cubiertos por una capa de color negro. Son temidos porque se alimentan de la felicidad y de los recuerdos alegres Necesitas algo mas?",
       " HOGWARTSBOT: No necesitan muros y agua para mantener a los prisioneros adentro, no cuando estan atrapados dentro de sus propias mentes, incapaces de tener un unico pensamiento feliz. Hay alguna otra cosa en la que te pueda ayudar?", " HOGWARTSBOT: Azkaban es una fortaleza en una isla ubicada en el medio del Mar del Norte. Sirve a la comunidad magica de Gran Bretaña como una prision para criminales convictos.  otra cosa que quieras saber?" ," HOGWARTSBOT: Desde 1717 el uso de cualquiera de las tres Maldiciones Imperdonables sobre otro ser humano acarreaba el castigo de cadena perpetua en Azkaban, otra cosa que quieras saber? ",
       " HOGWARTSBOT: El quidditch es el mejor deporte del mundo magico,¿juegas en alguna posicion ?",   " HOGWARTSBOT: El quidditch es el mas conocido ¿Cuál es tu escoba para el quidditch? ", " HOGWARTSBOT: El Quidditch es el deporte mas popular en la comunidad magica. Es una especie de futbol-baloncesto aereo que se juega volando sobre escobas. Necesitas algo mas? ",
       " HOGWARTSBOT: Se molestan con mucha facilidad. Nunca ofendais a ninguno, porque podria ser lo ultimo que hicierais. Quieres saber algo más?", " HOGWARTSBOT: Un hipogrifo es un animal magico que se obtiene al cruzar un caballo con un grifo. Necesitas algo mas? " ," HOGWARTSBOT: son orgullosos. Se molestan con mucha facilidad. Nunca ofendais a ninguno, porque podria ser lo ultimo que hicierais,  Hay alguna otra cosa en la que te pueda ayudar? ",
       " HOGWARTSBOT: Harry James Potter (n. el 31 de julio de 1980), es un mago de sangre mestiza, y el unico hijo de James y Lily Potter. otra cosa que quieras saber? ", " HOGWARTSBOT: Es la unica persona conocida que ha sobrevivido a la maldicion de Avada Kedavra, haciendolo en dos ocasiones. Necesitas algo mas? ", " HOGWARTSBOT:  Comienza a asistir a Hogwarts y es seleccionado en la Casa de Gryffindor. Se convierte en el mejor amigo de Ron Weasley y Hermione Granger, Hay alguna otra cosa en la que te pueda ayudar?",
       " HOGWARTSBOT: Ronald 'Ron' Bilius Weasley, nacido el 1 de marzo de 1980, es el hijo de Arthur y Molly Weasley, siendo el sexto de siete hijos ", " HOGWARTSBOT: Ron crecio en el hogar de su familia, La Madriguera, cerca de la villa de Ottery St. Catchpole en Devon. Ron tiene cinco hermanos, Bill, Charlie, Percy, Fred y George. Tambien tiene una hermana pequeña llamada Ginny. otra cosa que quieras saber? ", " HOGWARTSBOT: Lo seleccionaron para la casa de Gryffindor, como cualquier otro Weasley.  otra cosa que quieras saber?",
       " HOGWARTSBOT: Fue un gusto ayudarlo, distruta tu estadia en Hogwarts  ", " HOGWARTSBOT: Hogwarts es la mejor escuela del mundo magico, disfruta mucho", " HOGWARTSBOT: Adios, Cuando necesites ayuda no dudes en buscarme ", 
       " HOGWARTSBOT: Usa alohomora cuando olvides tus llaves Quieres saber algo mas? ", " HOGWARTSBOT: Los tres maleficios imperdonables son Avada kedavra, Crucius e Imperio, ¡Nunca los uses!, otra cosa que quieras saber?", "  HOGWARTSBOT: expelliarmus es el favorito de Harry, desarma de su varita a tu oponente Necesitas algo mas?",
       " HOGWARTSBOT: Los profesores son Minerva Mcgonagall de transformaciones, Rubius Hagrid de cuidado de criaturas magicas, pero ten cuidado en pociones con Snape, Quieres saber algo mas?", " HOGWARTSBOT: Algunos dicen que la profesora de adivinacion esta loca! y que Mcgonagall es muy estricta. Quieres saber algo mas? ", " HOGWARTSBOT: Dumbledore tambien fue profesor del colegio, pero hace muchos años, era el mejor en transformaciones. Quieres saber algo mas?",
       " HOGWARTSBOT: no logre entender tu pregunta porque es demasiado muggle, quizas quisiste decir ", " HOGWARTSBOT: No entiendo lo que quieres, puede que sea algo del mundo muggle, quizas quisiste decir ", " HOGWARTSBOT: La lechuza con lo que me decias no llego, la encontro un muggle quizas quisiste decir", "HOGWARTSBOT: No entiendo lo que quieres, quizas quisiste decir"]).

%idChatbot: Aridad 1, Palabras claves que permiten encontrar lo que busca el usuario.
 idChatbot(["Saludo", "casas", "Ravenclaw","Gryffindor","Slytherin","Hufflepuff", "historia","asignaturas" ,"Defensa","Adivinacion", "patronus" ,"dementor","Azkaban", "deportes",
 "Hipogrifo","Harry","Ron","fin","hechizos", "profesores",""]).
%usuarios: Aridad 2, contiene las frases necesarias para iniciar y concluir una conversación.
 usuarios(user1,[" yo soy ravenclaw" , "quien es harry ?  ", "que es un hipogrifo ?", "me gustaria conocer algunos hechizos", "cuales son las asignaturas ?", "quienes son los profesores ?"]).
 usuarios(user2,["mi casa es gryffindor", " quiero conocer algunos hechizos ", "cuales son las asignaturas de Hogwarts ?", " que es un dementor ? ",  "  quien es Harry ?", " hay deportes ? ",  " que es defensa contra las artes oscuras ?", " que hechizos son conocidos ?"]).
 usuarios(user3,[" quienes son los profesores ?", " me dijeron que un alumno se llama Ron ,  quien es ?", " cuales son las asignaturas ?", "¿ cuantos puntos tienen las casas ?", " Que es Azkaban ?"," Que es adivinacion ?, de que trata ?"]).